In [5]:
import numpy as np
from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.multicomp import MultiComparison

data = np.rec.array([
('Pat', 5),
('Pat', 4),
('Pat', 4),
('Pat', 3),
('Pat', 9),
('Pat', 4),
('Jack', 4),
('Jack', 8),
('Jack', 7),
('Jack', 5),
('Jack', 1),
('Jack', 5),
('Alex', 9),
('Alex', 8),
('Alex', 8),
('Alex', 10),
('Alex', 5),
('Alex', 10)], dtype = [('Archer','|U5'),('Score', '<i8')])
 
f, p = stats.f_oneway(data[data['Archer'] == 'Pat'].Score,
                      data[data['Archer'] == 'Jack'].Score,
                      data[data['Archer'] == 'Alex'].Score)
 
print ('One-way ANOVA')
print ('=============')
 
print ('F value:', f)
print ('P value:', p, '\n')

One-way ANOVA
F value: 4.999999999999998
P value: 0.021683749320078414 



In [10]:
data[data['Archer'] == 'Pat'].Score

array([5, 4, 4, 3, 9, 4])

In [11]:
data['Score']

array([ 5,  4,  4,  3,  9,  4,  4,  8,  7,  5,  1,  5,  9,  8,  8, 10,  5,
       10])

In [9]:
data['Ancher']

ValueError: no field of name Ancher

In [19]:
mc = MultiComparison(data['Score'], data['Archer'])
mc

In [17]:
result = mc.tukeyhsd()

In [14]:
print(result)

Multiple Comparison of Means - Tukey HSD,FWER=0.05
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
 Alex   Jack  -3.3333  -6.5755 -0.0911  True 
 Alex   Pat     -3.5   -6.7422 -0.2578  True 
 Jack   Pat   -0.1667  -3.4089  3.0755 False 
---------------------------------------------


In [15]:
print(mc.groupsunique)

['Alex' 'Jack' 'Pat']


In [20]:
data['Score']

array([ 5,  4,  4,  3,  9,  4,  4,  8,  7,  5,  1,  5,  9,  8,  8, 10,  5,
       10])

In [21]:
data['Archer']

array(['Pat', 'Pat', 'Pat', 'Pat', 'Pat', 'Pat', 'Jack', 'Jack', 'Jack',
       'Jack', 'Jack', 'Jack', 'Alex', 'Alex', 'Alex', 'Alex', 'Alex',
       'Alex'], dtype='<U5')

In [22]:
help(MultiComparison)

Help on class MultiComparison in module statsmodels.sandbox.stats.multicomp:

class MultiComparison(builtins.object)
 |  MultiComparison(data, groups, group_order=None)
 |  
 |  Tests for multiple comparisons
 |  
 |  Parameters
 |  ----------
 |  data : array
 |      independent data samples
 |  groups : array
 |      group labels corresponding to each data point
 |  group_order : list of strings, optional
 |      the desired order for the group mean results to be reported in. If
 |      not specified, results are reported in increasing order.
 |      If group_order does not contain all labels that are in groups, then
 |      only those observations are kept that have a label in group_order.
 |  
 |  Methods defined here:
 |  
 |  __init__(self, data, groups, group_order=None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  allpairtest(self, testfunc, alpha=0.05, method='bonf', pvalidx=1)
 |      run a pairwise test on all pairs with multiple test corre